#!/bin/sh

cp $1 $2 || exit 1
strip -s $2 || exit 1
sstrip -z $2 || exit 1
xz -9e $2 || exit 1
echo '#!/bin/sh' > $2 || exit 1
echo 'tail -n+3 $0|xzcat>/tmp/d;chmod +x /tmp/d;exec /tmp/d "$@"' >> $2 || exit 1
cat $2.xz >> $2 || exit 1
chmod +x $2 || exit 1
rm $2.xz || exit 1

