#!/usr/bin/env php
<?php
/* Author: Romain "Artefact2" Dalmaso <artefact2@gmail.com> */

/* This program is free software. It comes without any warranty, to the
 * extent permitted by applicable law. You can redistribute it and/or
 * modify it under the terms of the Do What The Fuck You Want To Public
 * License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

if($argc !== 2) {
	die("Usage: {$argv[0]} <xmfile>\n");
}

$file = $argv[1];

if(!file_exists($file) || !is_readable($file)) {
	die("File $file not found or not readable\n");
}

$fp = fopen($file, 'rb');
fseek($fp, 0, \SEEK_END);
$len = ftell($fp);
rewind($fp);

echo "static const unsigned char xmdata[".$len."] = {\n";

while(($char = fgetc($fp)) !== false) {
	echo ord($char).",";
}

echo "\n};\n";

fclose($fp);
